#Added 2 funny sentences.

print ('\nPlease enter the following:')
adjective = input('\nadjective:' ' ')
animal = input('animal:' ' ')
verb1 = input('verb:' ' ')
exclamation = input('exclamation:' ' ')
verb2 = input('verb:' ' ')
verb3 = input('verb:' ' ')
print('\nYour story is:')
print('\nThe other day, I was really in trouble. It all started when I saw a very')
print(''+ adjective.lower() + ' ' + animal.lower() + ' ' + verb1.lower() + ' ' 'down the hallway. ' '\"'+ exclamation.capitalize() +'!"'' I yelled. But all')
print('I could think to do was to' ' ' + verb2.lower() +' ' 'over and over. Miraculously,')
print('that caused it to stop, but not before it tried to' ' ' + verb3.lower() + ' ' )
print('right in front of my family.\n')
print(''"To everyone's amazement, the sluggish" ' '+ animal.lower() + ' at the dinner table suddenly ')
print('challenged my grandma to a slow-motion dance-off. With moves slower than ')
print('a'' '+ animal.lower() +'' '\'s'' commute, they ' ''+ verb1.lower() + ' ''and' ' '+ verb2.lower() +', transforming our mundane family ')
print('dinner into a hilarious spectacle. Who knew a tired'' '+ animal.lower() +'\'s' ' cry')
print('could bring about a night of sloth-inspired dance battles!\n')